language: java
sudo: false

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then 
    mvn clean deploy --settings target/travis/settings.xml; 
else 
    mvn clean verify --settings target/travis/settings.xml;
fi"

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "CaBphV3/Kj5IMV654/bOEYeXXA960L9UPxttmwgzq3GRTgJsuccVFmoQazh50Qr/tl6/3HLFJdbQ5N6uuqxsxDTba4nY6eiSlvJvZbLXeJBYPkCV6MP6XYHl3zyf6H8AuuPHsHY1jDLv3ZngeVzOvTXBuVmcYYqGTen32ZzzJlo="
    - secure: "XLpMDm1OmJVfmMFdua1mprIu1/ddeIFcGlOsGgrZ/cducGmLueeB+fODLlc8VKFUkmm1kpC9ugkNQgazaPeWvys+R7pqIAv8cWp8jfKPKAsPeUmnA1Y3zAqnYKmL7qdjVNMb08ikpW/MwqxX8t+GdPpZg+MKomvD3kHRdTF0VWA="
